<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/FingerprintProtocol.proto

namespace WhisperSystems\LibSignal\Fingerprint\FingerprintProtos\;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>textsecure.LogicalFingerprint</code>
 */
class LogicalFingerprint extends \Google\Protobuf\Internal\Message
{
    /**
     *  optional bytes identifier = 2;
     *
     * Generated from protobuf field <code>optional bytes content = 1;</code>
     */
    protected $content = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $content
     *            optional bytes identifier = 2;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\FingerprintProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     *  optional bytes identifier = 2;
     *
     * Generated from protobuf field <code>optional bytes content = 1;</code>
     * @return string
     */
    public function getContent()
    {
        return isset($this->content) ? $this->content : '';
    }

    public function hasContent()
    {
        return isset($this->content);
    }

    public function clearContent()
    {
        unset($this->content);
    }

    /**
     *  optional bytes identifier = 2;
     *
     * Generated from protobuf field <code>optional bytes content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->content = $var;

        return $this;
    }

}

