<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/LocalStorageProtocol.proto

namespace WhisperSystems\LibSignal\State\StorageProtos\;

if (false) {
    /**
     * This class is deprecated. Use WhisperSystems\LibSignal\State\StorageProtos\\SenderKeyStateStructure\SenderChainKey instead.
     * @deprecated
     */
    class SenderKeyStateStructure_SenderChainKey {}
}
class_exists(SenderKeyStateStructure\SenderChainKey::class);
@trigger_error('WhisperSystems\LibSignal\State\StorageProtos\\SenderKeyStateStructure_SenderChainKey is deprecated and will be removed in the next major release. Use WhisperSystems\LibSignal\State\StorageProtos\\SenderKeyStateStructure\SenderChainKey instead', E_USER_DEPRECATED);

