<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/LocalStorageProtocol.proto

namespace WhisperSystems\LibSignal\State\StorageProtos\;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>textsecure.SenderKeyRecordStructure</code>
 */
class SenderKeyRecordStructure extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .textsecure.SenderKeyStateStructure senderKeyStates = 1;</code>
     */
    private $senderKeyStates;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \WhisperSystems\LibSignal\State\StorageProtos\\SenderKeyStateStructure[]|\Google\Protobuf\Internal\RepeatedField $senderKeyStates
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\LocalStorageProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .textsecure.SenderKeyStateStructure senderKeyStates = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSenderKeyStates()
    {
        return $this->senderKeyStates;
    }

    /**
     * Generated from protobuf field <code>repeated .textsecure.SenderKeyStateStructure senderKeyStates = 1;</code>
     * @param \WhisperSystems\LibSignal\State\StorageProtos\\SenderKeyStateStructure[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSenderKeyStates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \WhisperSystems\LibSignal\State\StorageProtos\\SenderKeyStateStructure::class);
        $this->senderKeyStates = $arr;

        return $this;
    }

}

