<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/LocalStorageProtocol.proto

namespace WhisperSystems\LibSignal\State\StorageProtos;

if (false) {
    /**
     * This class is deprecated. Use WhisperSystems\LibSignal\State\StorageProtos\SenderKeyStateStructure\SenderSigningKey instead.
     * @deprecated
     */
    class SenderKeyStateStructure_SenderSigningKey {}
}
class_exists(SenderKeyStateStructure\SenderSigningKey::class);
@trigger_error('WhisperSystems\LibSignal\State\StorageProtos\SenderKeyStateStructure_SenderSigningKey is deprecated and will be removed in the next major release. Use WhisperSystems\LibSignal\State\StorageProtos\SenderKeyStateStructure\SenderSigningKey instead', E_USER_DEPRECATED);

