<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/LocalStorageProtocol.proto

namespace WhisperSystems\LibSignal\State\StorageProtos;

if (false) {
    /**
     * This class is deprecated. Use WhisperSystems\LibSignal\State\StorageProtos\SenderKeyStateStructure\SenderMessageKey instead.
     * @deprecated
     */
    class SenderKeyStateStructure_SenderMessageKey {}
}
class_exists(SenderKeyStateStructure\SenderMessageKey::class);
@trigger_error('WhisperSystems\LibSignal\State\StorageProtos\SenderKeyStateStructure_SenderMessageKey is deprecated and will be removed in the next major release. Use WhisperSystems\LibSignal\State\StorageProtos\SenderKeyStateStructure\SenderMessageKey instead', E_USER_DEPRECATED);

