<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/LocalStorageProtocol.proto

namespace WhisperSystems\LibSignal\State\StorageProtos;

if (false) {
    /**
     * This class is deprecated. Use WhisperSystems\LibSignal\State\StorageProtos\SessionStructure\Chain\MessageKey instead.
     * @deprecated
     */
    class SessionStructure_Chain_MessageKey {}
}
class_exists(SessionStructure\Chain\MessageKey::class);
@trigger_error('WhisperSystems\LibSignal\State\StorageProtos\SessionStructure_Chain_MessageKey is deprecated and will be removed in the next major release. Use WhisperSystems\LibSignal\State\StorageProtos\SessionStructure\Chain\MessageKey instead', E_USER_DEPRECATED);

