<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/LocalStorageProtocol.proto

namespace WhisperSystems\LibSignal\State\StorageProtos\;

if (false) {
    /**
     * This class is deprecated. Use WhisperSystems\LibSignal\State\StorageProtos\\SessionStructure\PendingKeyExchange instead.
     * @deprecated
     */
    class SessionStructure_PendingKeyExchange {}
}
class_exists(SessionStructure\PendingKeyExchange::class);
@trigger_error('WhisperSystems\LibSignal\State\StorageProtos\\SessionStructure_PendingKeyExchange is deprecated and will be removed in the next major release. Use WhisperSystems\LibSignal\State\StorageProtos\\SessionStructure\PendingKeyExchange instead', E_USER_DEPRECATED);

