<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/LocalStorageProtocol.proto

namespace WhisperSystems\LibSignal\State\StorageProtos;

if (false) {
    /**
     * This class is deprecated. Use WhisperSystems\LibSignal\State\StorageProtos\SessionStructure\PendingPreKey instead.
     * @deprecated
     */
    class SessionStructure_PendingPreKey {}
}
class_exists(SessionStructure\PendingPreKey::class);
@trigger_error('WhisperSystems\LibSignal\State\StorageProtos\SessionStructure_PendingPreKey is deprecated and will be removed in the next major release. Use WhisperSystems\LibSignal\State\StorageProtos\SessionStructure\PendingPreKey instead', E_USER_DEPRECATED);

